# This is a configuration file for the continuous delivery service provided
# by AppVeyor.com. Its purpose is to automatically build the CEF Python project.
# Please refer to https://github.com/cztomczak/cefpython
# for more information on CEF Python.

os: Visual Studio 2015

configuration:
  - Release

environment:
  PYTHON: "C:\\Python27-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install --upgrade -r tools/requirements.txt
  - ps: Start-FileDownload 'https://github.com/cztomczak/cefpython/releases/download/v57-upstream/cef57_3.2987.1601.gf035232_win64.zip'

before_build:
  - mkdir build
  - 7z x cef57_3.2987.1601.gf035232_win64.zip -obuild

build_script:
  - cd build
  - https://github.com/cztomczak/cefpython/releases/download/v57-upstream/cef57_3.2987.1601.gf035232_win64.zip
  # Doesnt work? CIPD seems 'stuck'
  # - echo "Building CEF..."
  #- python ../tools/automate.py --build-cef --ninja-jobs 4
  - echo "Building CEF Python..."
  - python ../tools/build.py 57.3
