# This is a configuration file for the continuous delivery service provided
# by AppVeyor.com. Its purpose is to automatically build the CEF Python project.
# Please refer to https://github.com/cztomczak/cefpython
# for more information on CEF Python.

os: Visual Studio 2015

environment:
  PYTHON: "C:\\Python27-x64"
  CEF_VERSION: "3.3029.1604.g364cd86"

install:
  - ps: Start-FileDownload 'https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip'
  - 7z x ninja-win.zip -oc:\projects\ninja
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;c:\\projects\\ninja;%PATH%"
  - pip install --upgrade -r tools/requirements.txt

before_build:
  - ps: Start-FileDownload 'http://opensource.spotify.com/cefbuilds/cef_binary_3.3029.1604.g364cd86_windows64.tar.bz2'
  - mkdir build
  - 7z x cef_binary_3.3029.1604.g364cd86_windows64.tar.bz2
  - 7z x cef_binary_3.3029.1604.g364cd86_windows64.tar -obuild
  - copy src\windows\py27\stdint.h "%LocalAppData%\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include"

build_script:
#  - cd build
#  - echo "Put prebuilt CEF in place..."
#  - python ../tools/automate.py --prebuilt-cef
#  - echo "Building CEF Python..."
#  - python ../tools/build.py 58.0
